services:
  web:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_DOMAIN
    ports:
      - 3000:3000
    develop:
      watch:
        - path: .
          action: rebuild
    env_file:
      - .env
